---
title: "Solutions to A Modern Approach to Regression with R"
author: "Johan Larsson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
github-repo: jolars/MARsolutions
description: "This book contains solutions to the problems in the book A Modern Approach to Regression With R, third edition, by Sheather. It is provided as a github repository so that anybody may contribute to its development."
---

```{r setup-options, include = FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
  fig.pos = "!htbp"
)

lattice::lattice.options(default.theme = list(
  fontsize = list(text = 10, points = 8)  
))

options(digits = 2)

```

# Preface {-}

This book contains solutions to the problems in the book A Modern Approach to Regression With R, third edition, by Sheather. It is provided as a github repository so that anybody may contribute to its development.

## Dependencies {-}

You are going to need the following packages to run all the solutions in the
book:

```{r, message = FALSE}
library(readr)
library(knitr)
library(dplyr)
library(tidyr)
library(lattice)
library(latticeExtra)
```





